//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flock.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuackLike
    {
        public int Id { get; set; }
        public int QuackId { get; set; }
        public int UserId { get; set; }
        public bool Active { get; set; }
    
        public virtual Quack Quack { get; set; }
        public virtual User User { get; set; }
    }
}
