//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flock.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Quacks = new HashSet<Quack>();
            this.UserInterests = new HashSet<UserInterest>();
            this.UserProjects = new HashSet<UserProject>();
            this.QuackLikes = new HashSet<QuackLike>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Active { get; set; }
        public string AdditionalDetails { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte[] CoverImage { get; set; }
        public byte[] ProfileImage { get; set; }
        public string EmailId { get; set; }
        public string Project { get; set; }
        public string Interests { get; set; }
    
        public virtual ICollection<Quack> Quacks { get; set; }
        public virtual ICollection<UserInterest> UserInterests { get; set; }
        public virtual ICollection<UserProject> UserProjects { get; set; }
        public virtual ICollection<QuackLike> QuackLikes { get; set; }
    }
}
